import os
import json

# Setup paths relative to script location
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
PODCASTS_DIR = os.path.join(ROOT_DIR, "podcasts")
OUTPUT_FILE = os.path.join(ROOT_DIR, "data", "podcast-data.js")

def parse_time(time_str):
    if not time_str:
        return 0.0
    time_str = time_str.strip().replace(",", ".")
    parts = time_str.split(":")
    if len(parts) == 3:
        try:
            return float(parts[0]) * 3600 + float(parts[1]) * 60 + float(parts[2])
        except ValueError:
            return 0.0
    return 0.0

def parse_subtitle(content):
    lines = content.replace("\r", "").split("\n")
    transcript = []
    current_item = None
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        if line.startswith("WEBVTT"):
            continue
            
        if line.isdigit():
            if current_item:
                transcript.append(current_item)
            current_item = {"start": 0.0, "end": 0.0, "text": ""}
        elif "-->" in line:
            times = line.split("-->")
            if len(times) == 2:
                if not current_item:
                    current_item = {"start": 0.0, "end": 0.0, "text": ""}
                current_item["start"] = parse_time(times[0])
                current_item["end"] = parse_time(times[1])
        elif current_item:
            current_item["text"] = (current_item["text"] + " " + line).strip() if current_item["text"] else line
            
    if current_item:
        transcript.append(current_item)
    return transcript

def scan():
    print("----------------------------------------------------")
    print("🎙️ STARTING PYTHON PODCAST DIRECTORY SCANNER...")
    print("----------------------------------------------------")
    
    if not os.path.exists(PODCASTS_DIR):
        print(f"📁 Creating directory: {PODCASTS_DIR}")
        os.makedirs(PODCASTS_DIR)
        
    files = os.listdir(PODCASTS_DIR)
    audio_files = [f for f in files if f.lower().endswith(".mp3")]
    audio_files.sort()
    
    print(f"🔍 Found {len(audio_files)} MP3 files in /podcasts")
    
    podcasts = []
    
    for index, file in enumerate(audio_files):
        base_name, _ = os.path.splitext(file)
        
        # Guess Speaker and Title
        speaker = "Unknown Speaker"
        title = base_name
        
        if "-" in base_name:
            parts = base_name.split("-")
            speaker = parts[0].strip()
            title = "-".join(parts[1:]).strip()
            
        # Search for matching subtitle (.srt or .vtt)
        sub_file = None
        for f in files:
            f_lower = f.lower()
            if f_lower == f"{base_name.lower()}.srt" or f_lower == f"{base_name.lower()}.vtt":
                sub_file = f
                break
                
        transcript = []
        if sub_file:
            sub_path = os.path.join(PODCASTS_DIR, sub_file)
            with open(sub_path, "r", encoding="utf-8") as sf:
                content = sf.read()
            transcript = parse_subtitle(content)
            print(f"✅ [{index + 1}] Bound subtitles: \"{sub_file}\" ({len(transcript)} lines)")
        else:
            print(f"⚠️ [{index + 1}] Warning: No subtitle found for \"{file}\". Please place a matching .srt file in /podcasts.")
            
        # Check for zero-byte files to use public streaming MP3s
        file_path = os.path.join(PODCASTS_DIR, file)
        file_size = os.path.getsize(file_path)
        audio_url = f"podcasts/{file}"
        duration = "Auto"
        
        if file_size == 0:
            if title == "Why Music Helps You Learn English":
                audio_url = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
                duration = "6:12"
            elif title == "The Magic of Lifelong Learning":
                audio_url = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3"
                duration = "7:05"
                
        podcasts.append({
            "id": f"p-{index + 1}",
            "title": title,
            "speaker": speaker,
            "level": "Podcast Level",
            "desc": f"Luyện nghe bài học tiếng Anh chủ đề: {title}.",
            "audioUrl": audio_url,
            "image": "🎙️",
            "duration": duration,
            "transcript": transcript
        })
        
    # Generate static Javascript structure
    js_content = (
        "// ==========================================================================\n"
        "// Learning English - Compiled Podcast Database (Auto-generated by scanner)\n"
        "// Do not modify directly. Run: python scratch/scan_postcast.py\n"
        "// ==========================================================================\n\n"
        f"const PODCAST_DATA = {json.dumps(podcasts, indent=4, ensure_ascii=False)};\n"
    )
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as out_f:
        out_f.write(js_content)
        
    print("----------------------------------------------------")
    print(f"🎉 SUCCESS: Compiled {len(podcasts)} podcasts into {OUTPUT_FILE}")
    print("----------------------------------------------------")

if __name__ == "__main__":
    scan()